version: "3.9"

services:
  system_db:
    image: postgres:15
    container_name: database
    env_file:
      - backend/.env
    ports:
      - "5432:5432"
    volumes:
      - system_pgdata:/var/lib/postgresql/data

  backend:
    build: ./backend
    container_name: backend
    ports:
      - "3001:3000"
      - "5555:5555"
    depends_on:
      - system_db
    env_file:
      - backend/.env
    volumes:
      - ./backend:/app
      - /app/node_modules

  storage:
    build: ./storage
    container_name: storage
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"   # S3 API
      - "9001:9001"   # Web UI
    env_file:
      - storage/.env
    volumes:
      - bucket:/data

volumes:
  system_pgdata:
  bucket:
